name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          DEPOT_PROJECT_ID: ${{ secrets.DEPOT_PROJECT_ID }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add DEPOT_PROJECT_ID="$DEPOT_PROJECT_ID" RAILWAY_PROJECT_ID="$RAILWAY_PROJECT_ID" RAILWAY_SERVICE_ID="$RAILWAY_SERVICE_ID" RAILWAY_TOKEN="$RAILWAY_TOKEN" --repo sbtechpal/depot-railway-build
          depot ci secrets add DEPOT_TOKEN --value "${{ secrets.DEPOT_TOKEN }}" --repo sbtechpal/depot-railway-build
